apiVersion: v1
kind: Service
metadata:
  name: msmicroservice-marcomartinez
  labels:
    app: examen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: examen
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msmicroservice-marcomartinez
spec:
  selector:
    matchLabels:
      app: examen
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: examen
        version: v1
    spec:
      containers:
        - name: examen
          image: martinezl/msmicroservice
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi        
          ports:
            - containerPort: 8080